"""Individual school athletic scrapers.

Each school gets its own deterministic scraper script.
Generated by discovery agent using Playwright to inspect live sites.

Structure:
    scrapers/schools/{state}/{nces_id}.py
"""

# This directory will contain 7,000+ individual scraper scripts
# Generated by: scripts/discover_schools.py (orchestrated by Claude)
