"""ABLE Charter School athletic data scraper.

Generated by discovery agent using Playwright MCP.
School: ABLE Charter School
NCES ID: 060162813064
Website: www.ablecharter.com
Athletic URL: https://www.ablecharter.com/apps/pages/index.jsp?uREC_ID=4361292&type=d
Generated: 2026-02-26

Data available:
- Sports offered (Cross Country, Volleyball, Soccer, Basketball, Track, Baseball, Softball, etc.)
- Coach contact information
- Tryout dates
- Athletic handbook
"""

from playwright.async_api import async_playwright
import os
from datetime import datetime
from typing import Optional
import re

# Oxylabs proxy credentials (REQUIRED)
PROXY_SERVER = "ddc.oxylabs.io:8001"
PROXY_USERNAME = os.environ.get("OXYLABS_USERNAME")
PROXY_PASSWORD = os.environ.get("OXYLABS_PASSWORD")


async def scrape_able_charter_athletics() -> dict:
    """
    Scrape athletic data from ABLE Charter School website.

    Returns:
        Dict with sports, coaches, tryouts, and contact info
    """
    if not PROXY_USERNAME or not PROXY_PASSWORD:
        raise ValueError("Oxylabs credentials not set")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": PROXY_SERVER,
                "username": PROXY_USERNAME,
                "password": PROXY_PASSWORD,
            },
            headless=True,
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )

        page = await context.new_page()

        # Navigate to athletics home
        await page.goto("https://www.ablecharter.com/apps/pages/index.jsp?uREC_ID=4361292&type=d")
        await page.wait_for_load_state("domcontentloaded")

        # Extract sports offered
        sports_data = {
            "fall": [],
            "winter": [],
            "spring": []
        }

        # Parse sports from the page content
        content = await page.content()

        # Extract fall sports
        fall_match = re.search(r"Fall:(.*?)(?=Winter:|$)", content, re.DOTALL)
        if fall_match:
            fall_text = fall_match.group(1).strip()
            fall_sports = [s.strip() for s in re.split(r"•|\*", fall_text) if s.strip() and "competes" not in s.lower() and "middle" not in s.lower()]
            sports_data["fall"] = [s for s in fall_sports if s]

        # Extract winter sports
        winter_match = re.search(r"Winter:(.*?)(?=Spring:|$)", content, re.DOTALL)
        if winter_match:
            winter_text = winter_match.group(1).strip()
            winter_sports = [s.strip() for s in re.split(r"•|\*", winter_text) if s.strip()]
            sports_data["winter"] = [s for s in winter_sports if "home field" not in s.lower()]

        # Extract spring sports
        spring_match = re.search(r"Spring:(.*?)(?=\"First Day|$)", content, re.DOTALL)
        if spring_match:
            spring_text = spring_match.group(1).strip()
            spring_sports = [s.strip() for s in re.split(r"•|\*", spring_text) if s.strip() and "Tryouts" not in s and "home field" not in s.lower()]
            sports_data["spring"] = [s for s in spring_sports if s]

        # Extract coach emails
        coaches = re.findall(r"[\w.-]+@[\w.-]+\.com", content)

        # Extract tryout dates
        tryouts = {}
        for match in re.finditer(r"(?:Girls |Boys )?(\w+(?: & \w+)?) Tryouts(?: (?:Spring|Fall|Winter))? ([A-Z][a-z]+ \d+,? \d+)(?:,|\.|\n)", content):
            sport = match.group(1)
            date = match.group(2)
            tryouts[sport] = date

        # Get athletic handbook link if exists
        handbook_link = None
        try:
            handbook_elem = await page.query_selector("a:has-text('Athletic Handbook')")
            if handbook_elem:
                handbook_link = await handbook_elem.get_attribute("href")
        except:
            pass

        await browser.close()

        return {
            "nces_id": "060162813064",
            "school_name": "ABLE Charter School",
            "athletic_url": "https://www.ablecharter.com/apps/pages/index.jsp?uREC_ID=4361292&type=d",
            "scraped_at": datetime.now().isoformat(),
            "sports": sports_data,
            "coaches": coaches,
            "tryouts": tryouts,
            "handbook_url": handbook_link,
            "raw_content": content[:5000],  # First 5000 chars for reference
        }


async def main():
    """Main entry point for running the scraper."""
    result = await scrape_able_charter_athletics()
    print(f"Scraped {result['school_name']}")
    print(f"Sports: Fall={len(result['sports']['fall'])}, Winter={len(result['sports']['winter'])}, Spring={len(result['sports']['spring'])}")
    print(f"Coaches found: {len(result['coaches'])}")
    print(f"Tryouts scheduled: {len(result['tryouts'])}")
    return result


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
