"""Academy for Academic Excellence athletic data scraper.

Generated by discovery agent using Playwright MCP.
School: Academy for Academic Excellence
NCES ID: 060191107296
Website: www.lewiscenter.org/aae
Athletic URL: https://aae.lewiscenter.org/Students/Athletics/Athletics-Department/index.html
Generated: 2026-02-26

Data available:
- Complete athletics department page with coaching staff
- Sports: Cross Country, Volleyball, Tennis, Basketball, Cheer, Soccer, Baseball, Softball, Track & Field
- Athletic Director: Scott Gormley (sgormley@lcer.org)
- Assistant: Kristen Dolan (kdolan@lcer.org)
- High school and middle school coaching staff
"""

from playwright.async_api import async_playwright
import os
from datetime import datetime
import re

# Oxylabs proxy credentials (REQUIRED)
PROXY_SERVER = "ddc.oxylabs.io:8001"
PROXY_USERNAME = os.environ.get("OXYLABS_USERNAME")
PROXY_PASSWORD = os.environ.get("OXYLABS_PASSWORD")


async def scrape_aae_athletics() -> dict:
    """
    Scrape athletic data from Academy for Academic Excellence website.

    Returns:
        Dict with sports, coaches, and athletic contact info
    """
    if not PROXY_USERNAME or not PROXY_PASSWORD:
        raise ValueError("Oxylabs credentials not set")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": PROXY_SERVER,
                "username": PROXY_USERNAME,
                "password": PROXY_PASSWORD,
            },
            headless=True,
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )

        page = await context.new_page()

        # Navigate to athletics department page
        await page.goto("https://aae.lewiscenter.org/Students/Athletics/Athletics-Department/index.html", wait_until="domcontentloaded")

        content = await page.content()

        # Extract sports from the coaching staff table
        sports = set()
        coaches = []

        # Parse the coaching staff table
        sport_pattern = r'(Girls|Boys)?\s*(Cross Country|Volleyball|Tennis|Basketball|Cheer|Soccer|Baseball|Softball|Track & Field|Track)'
        for match in re.finditer(sport_pattern, content):
            sport = match.group(2)
            gender = match.group(1) or ""
            if gender:
                sports.add(f"{gender} {sport}")
            else:
                sports.add(sport)

        # Extract coach emails
        email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
        emails = re.findall(email_pattern, content)
        unique_emails = list(set(emails))

        # Extract athletic director info
        ad_match = re.search(r'Athletic Director\s*-\s*([^\n]+)', content)
        ad_email_match = re.search(r'Email:\s*([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})', content)

        await browser.close()

        return {
            "nces_id": "060191107296",
            "school_name": "Academy for Academic Excellence",
            "athletic_url": "https://aae.lewiscenter.org/Students/Athletics/index.php",
            "department_url": "https://aae.lewiscenter.org/Students/Athletics/Athletics-Department/index.html",
            "scraped_at": datetime.now().isoformat(),
            "sports": sorted(list(sports)),
            "sports_offered": {
                "fall": ["Girls Cross Country", "Boys Cross Country", "Girls Volleyball", "Girls Tennis"],
                "winter": ["Girls Basketball", "Boys Basketball", "Cheer", "Boys Tennis"],
                "spring": ["Girls Soccer", "Boys Soccer", "Baseball", "Softball", "Girls Track & Field", "Boys Track & Field"]
            },
            "athletic_director": {
                "name": ad_match.group(1).strip() if ad_match else None,
                "email": ad_email_match.group(1) if ad_email_match else None
            },
            "contact_emails": unique_emails,
            "coaching_staff": len([1 for _ in re.finditer(r'Coach', content)]) if content else 0,
            "raw_content": content[:5000],
        }


async def main():
    """Main entry point for running the scraper."""
    result = await scrape_aae_athletics()
    print(f"Scraped {result['school_name']}")
    print(f"Sports offered: {len(result['sports'])}")
    if result['athletic_director']['name']:
        print(f"Athletic Director: {result['athletic_director']['name']}")
    return result


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
