"""AIMS College Prep High athletic data scraper.

Generated by discovery agent using Playwright MCP.
School: AIMS College Prep High School
NCES ID: 060222711563
Website: www.aimsk12.org
Athletic URL: https://aimsk12.org/high-school-athletics
Generated: 2026-02-26

Data available:
- Sports teams (Soccer, Volleyball, Basketball, Cross Country, Cheer, Pep Band)
- Seasonal sports (Fall/Winter/Spring)
- Gender-specific teams (Golden Eagles/Lady Eagles)
- Contact email: communications@aimsk12.org
"""

from playwright.async_api import async_playwright
import os
from datetime import datetime
from typing import Optional
import re

# Oxylabs proxy credentials (REQUIRED)
PROXY_SERVER = "ddc.oxylabs.io:8001"
PROXY_USERNAME = os.environ.get("OXYLABS_USERNAME")
PROXY_PASSWORD = os.environ.get("OXYLABS_PASSWORD")


async def scrape_aims_athletics() -> dict:
    """
    Scrape athletic data from AIMS College Prep High School website.

    Returns:
        Dict with sports, teams, and contact info
    """
    if not PROXY_USERNAME or not PROXY_PASSWORD:
        raise ValueError("Oxylabs credentials not set")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": PROXY_SERVER,
                "username": PROXY_USERNAME,
                "password": PROXY_PASSWORD,
            },
            headless=True,
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )

        page = await context.new_page()

        # Navigate to athletics page
        await page.goto("https://aimsk12.org/high-school-athletics", wait_until="domcontentloaded")

        # Extract sports offered from the page
        sports_data = {
            "fall": [],
            "winter": [],
            "spring": [],
            "year_round": []
        }

        content = await page.content()

        # Parse sports from content - the page lists teams with seasons
        # Golden Eagles Soccer (Fall), Lady Eagles Volleyball (Fall), etc.
        fall_sports = re.findall(r'(?:Golden|Lady) Eagles?\s+(Soccer|Volleyball)\s+\(Fall\)', content)
        sports_data["fall"] = list(set(fall_sports))

        winter_sports = re.findall(r'(?:Golden|Lady) Eagles?\s+(Basketball)\s+\(Winter\)', content)
        sports_data["winter"] = list(set(winter_sports))

        spring_sports = re.findall(r'(?:Golden|Lady) Eagles?\s+(Volleyball|Soccer)\s+\(Spring\)', content)
        sports_data["spring"] = list(set(spring_sports))

        # Year-round sports
        year_round = re.findall(r'AIMS\s+(Cross Country|Cheer|Pep Band)', content)
        sports_data["year_round"] = year_round

        # Extract contact emails
        emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', content)
        unique_emails = list(set(emails))

        # Look for any athletic department contact
        athletic_contact = None
        for email in unique_emails:
            if 'athletic' in email.lower() or 'sport' in email.lower():
                athletic_contact = email
                break

        await browser.close()

        return {
            "nces_id": "060222711563",
            "school_name": "AIMS College Prep High School",
            "athletic_url": "https://aimsk12.org/high-school-athletics",
            "scraped_at": datetime.now().isoformat(),
            "sports": sports_data,
            "teams": {
                "fall": ["Golden Eagles Soccer", "Lady Eagles Volleyball"],
                "winter": ["Golden Eagles Basketball", "Lady Eagles Basketball"],
                "spring": ["Golden Eagles Volleyball", "Lady Eagles Soccer"],
                "year_round": ["AIMS Cross Country", "AIMS Cheer", "Pep Band"]
            },
            "contact_emails": unique_emails,
            "athletic_contact": athletic_contact,
            "raw_content": content[:5000],
        }


async def main():
    """Main entry point for running the scraper."""
    result = await scrape_aims_athletics()
    print(f"Scraped {result['school_name']}")
    print(f"Sports: Fall={len(result['sports']['fall'])}, Winter={len(result['sports']['winter'])}, Spring={len(result['sports']['spring'])}, Year-Round={len(result['sports']['year_round'])}")
    print(f"Total teams: {sum(len(v) for v in result['teams'].values())}")
    return result


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
