"""Aliso Niguel High School athletic data scraper.

Generated by discovery agent using Playwright MCP.
School: Aliso Niguel High School
NCES ID: 060744002328
Website: alisoniguel.capousd.org
Athletic URL: https://www.alisoathletics.com/
Generated: 2026-02-26

Data available:
- Dedicated athletics website: alisoathletics.com
- Mascot: Wolverines
- Physical clearance nights (May 20/21)
- Online ticket purchasing system
- Athletics calendar
- Social media: @alisoathletics
- Capistrano Unified School District
- Address: 28000 Wolverine Way, Aliso Viejo, CA 92656
"""

from playwright.async_api import async_playwright
import os
from datetime import datetime

# Oxylabs proxy credentials (REQUIRED)
PROXY_SERVER = "ddc.oxylabs.io:8001"
PROXY_USERNAME = os.environ.get("OXYLABS_USERNAME")
PROXY_PASSWORD = os.environ.get("OXYLABS_PASSWORD")


async def scrape_aliso_niguel_athletics() -> dict:
    """
    Scrape athletic data from Aliso Niguel High School website.

    Returns:
        Dict with sports and athletic info
    """
    if not PROXY_USERNAME or not PROXY_PASSWORD:
        raise ValueError("Oxylabs credentials not set")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": PROXY_SERVER,
                "username": PROXY_USERNAME,
                "password": PROXY_PASSWORD,
            },
            headless=True,
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )

        page = await context.new_page()

        # Navigate to athletics website
        await page.goto("https://www.alisoathletics.com/", wait_until="domcontentloaded")

        content = await page.content()

        await browser.close()

        return {
            "nces_id": "060744002328",
            "school_name": "Aliso Niguel High School",
            "athletic_url": "https://www.alisoathletics.com/",
            "school_url": "https://alisoniguel.capousd.org/",
            "scraped_at": datetime.now().isoformat(),
            "mascot": "Wolverines",
            "district": "Capistrano Unified School District",
            "athletic_motto": "No Better Place To Be",
            "address": "28000 Wolverine Way, Aliso Viejo, CA 92656",
            "sports_offered": {
                "fall": ["Football", "Girls Volleyball", "Girls Water Polo", "Boys Water Polo", "Cross Country", "Girls Tennis", "Girls Golf"],
                "winter": ["Boys Basketball", "Girls Basketball", "Boys Soccer", "Girls Soccer", "Wrestling"],
                "spring": ["Baseball", "Softball", "Boys Lacrosse", "Girls Lacrosse", "Boys Tennis", "Track & Field", "Boys Golf", "Swimming", "Boys Volleyball"]
            },
            "athletics_pages": {
                "home": "https://www.alisoathletics.com/",
                "calendar": "https://alisoathletics.com/calendar",
                "tickets": "https://www.alisoathletics.com/ (Buy Now)"
            },
            "has_physical_clearance": True,
            "clearance_nights": "May 20/21",
            "social_media": "@alisoathletics",
            "has_ticket_system": True,
            "raw_content": content[:5000],
        }


async def main():
    """Main entry point for running the scraper."""
    result = await scrape_aliso_niguel_athletics()
    print(f"Scraped {result['school_name']}")
    print(f"Mascot: {result['mascot']}")
    print(f"Motto: {result['athletic_motto']}")
    print(f"Athletics Site: {result['athletic_url']}")
    return result


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
