"""Agoura High School athletic data scraper.

Generated by discovery agent using Playwright MCP.
School: Agoura High School
NCES ID: 062100002518
Website: www.agourahighschool.net
Athletic URL: https://sites.google.com/lvusd.org/agourachargers
Generated: 2026-02-26

Data available:
- Comprehensive athletics program with "Tradition of Excellence"
- CIF Southern Section competition
- Marmonte League participation
- Multiple league championships (Football, Boys Soccer, Boys/Girls Water Polo, Boys/Girls Lacrosse, Boys Basketball, Baseball, Flag)
- Athletic clearance process
- NCAA student-athletes (Class of 2025)
- Sports: Football, Flag Football, Volleyball, Water Polo, Cross Country, Basketball, Soccer, Wrestling, Baseball, Softball, Track, Tennis, Golf, Lacrosse
- Kinesiology & Sport Medicine Academy
"""

from playwright.async_api import async_playwright
import os
from datetime import datetime
import re

# Oxylabs proxy credentials (REQUIRED)
PROXY_SERVER = "ddc.oxylabs.io:8001"
PROXY_USERNAME = os.environ.get("OXYLABS_USERNAME")
PROXY_PASSWORD = os.environ.get("OXYLABS_PASSWORD")


async def scrape_agoura_high_athletics() -> dict:
    """
    Scrape athletic data from Agoura High School website.

    Returns:
        Dict with sports, championships, and athletic info
    """
    if not PROXY_USERNAME or not PROXY_PASSWORD:
        raise ValueError("Oxylabs credentials not set")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": PROXY_SERVER,
                "username": PROXY_USERNAME,
                "password": PROXY_PASSWORD,
            },
            headless=True,
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )

        page = await context.new_page()

        # Navigate to athletics page (Google Sites)
        await page.goto("https://sites.google.com/lvusd.org/agourachargers", wait_until="domcontentloaded")

        content = await page.content()

        # Extract league championship info
        championships = []
        champ_pattern = r'([A-Z][A-Z\s]+)\n.*?\n(\d{4})'
        for match in re.finditer(champ_pattern, content):
            sport = match.group(1).strip()
            year = match.group(2)
            if len(sport) > 3 and len(sport) < 30:
                championships.append({"sport": sport, "year": year})

        # Check for NCAA athletes
        ncaa_pattern = r'([A-Z][a-z]+ [A-Z][a-z]+)\n\n([A-Za-z,&\s]+)\n\n([A-Za-z .]+)'
        ncaa Athletes = []
        for match in re.finditer(ncaa_pattern, content):
            name = match.group(1)
            sports = match.group(2)
            college = match.group(3)
            if 'Univ.' in college or 'College' in college:
                ncaa_athletes.append({
                    "name": name,
                    "sports": sports.strip(),
                    "college": college.strip()
                })

        await browser.close()

        return {
            "nces_id": "062100002518",
            "school_name": "Agoura High School",
            "athletic_url": "https://sites.google.com/lvusd.org/agourachargers",
            "scraped_at": datetime.now().isoformat(),
            "mascot": "Chargers",
            "league": "Marmonte League",
            "cif_section": "CIF Southern Section",
            "sports_offered": {
                "fall": ["Football", "Girls Volleyball", "Girls Water Polo", "Boys Water Polo", "Cross Country", "Girls Tennis", "Girls Golf"],
                "winter": ["Boys Basketball", "Girls Basketball", "Boys Soccer", "Girls Soccer", "Wrestling"],
                "spring": ["Baseball", "Softball", "Boys Volleyball", "Boys Lacrosse", "Girls Lacrosse", "Boys Tennis", "Track & Field", "Boys Golf", "Swimming"]
            },
            "recent_championships": championships[:20],  # Recent league championships
            "tradition": "Tradition of Excellence",
            "has_athletic_clearance": True,
            "has_sport_medicine_academy": True,
            "sport_medicine_url": "https://sites.google.com/lvusd.org/agourachargers/sports-medicine",
            "ncaa_athletes": ncaa_athletes[:10],  # Recent NCAA signees
            "raw_content": content[:5000],
        }


async def main():
    """Main entry point for running the scraper."""
    result = await scrape_agoura_high_athletics()
    print(f"Scraped {result['school_name']}")
    print(f"Mascot: {result['mascot']}")
    print(f"League: {result['league']}")
    print(f"Recent Championships: {len(result['recent_championships'])}")
    print(f"NCAA Athletes (Class of 2025): {len(result['ncaa_athletes'])}")
    return result


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
