"""Alexander Hamilton Senior High School athletic data scraper.

Generated by discovery agent using Playwright MCP.
School: Alexander Hamilton Senior High School
NCES ID: 062271003064
Website: hamiltonhs.org
Athletic URL: https://hamiltonhs.lausd.org/apps/pages/index.jsp?uREC_ID=3368403&type=d&pREC_ID=2358656
Generated: 2026-02-26

Data available:
- Comprehensive athletics program with "Expect To Win" mentality
- Athletic Director: Ken Turner
- Assistant AD: Chey Gaston Lewis
- Athletics mission and vision
- Athletic news and events
- Sports teams with tryouts (Baseball, Boys Volleyball mentioned)
- Athletic forms and clearance process
- Athletics calendar
- Schoology groups integration
"""

from playwright.async_api import async_playwright
import os
from datetime import datetime
import re

# Oxylabs proxy credentials (REQUIRED)
PROXY_SERVER = "ddc.oxylabs.io:8001"
PROXY_USERNAME = os.environ.get("OXYLABS_USERNAME")
PROXY_PASSWORD = os.environ.get("OXYLABS_PASSWORD")


async def scrape_hamilton_high_athletics() -> dict:
    """
    Scrape athletic data from Alexander Hamilton Senior High School website.

    Returns:
        Dict with sports, athletic department, and contact info
    """
    if not PROXY_USERNAME or not PROXY_PASSWORD:
        raise ValueError("Oxylabs credentials not set")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": PROXY_SERVER,
                "username": PROXY_USERNAME,
                "password": PROXY_PASSWORD,
            },
            headless=True,
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )

        page = await context.new_page()

        # Navigate to athletics page
        await page.goto("https://hamiltonhs.lausd.org/apps/pages/index.jsp?uREC_ID=3368403&type=d&pREC_ID=2358656", wait_until="domcontentloaded")

        content = await page.content()

        # Extract contact info
        ad_match = re.search(r'Ken Turner\s*Athletics Director', content)
        asst_ad_match = re.search(r'Chey Gaston Lewis\s*Teacher & Assistant AD', content)
        phone_match = re.search(r'Phone:\s*\((\d{3}\)\s*(\d{3}-\d{4})', content)

        # Look for athletic news/events
        tryouts = []
        tryout_pattern = r'(\w+(?:\s+\w+)?)\s*Tryouts.*?(\d{1,2}-\d{1,2}-\d{4})'
        for match in re.finditer(tryout_pattern, content, re.IGNORECASE):
            tryouts.append({
                "sport": match.group(1),
                "date": match.group(2)
            })

        await browser.close()

        return {
            "nces_id": "062271003064",
            "school_name": "Alexander Hamilton Senior High School",
            "athletic_url": "https://hamiltonhs.lausd.org/apps/pages/index.jsp?uREC_ID=3368403&type=d&pREC_ID=2358656",
            "scraped_at": datetime.now().isoformat(),
            "mascot": "Yankees",
            "district": "Los Angeles Unified School District",
            "athletic_motto": "Expect To Win",
            "athletic_department": {
                "athletic_director": "Ken Turner",
                "assistant_ad": "Chey Gaston Lewis"
            },
            "address": "2955 S Robertson Blvd, Los Angeles, CA 90034",
            "phone": "(310) 280-1400",
            "sports_offered": {
                "fall": ["Football", "Girls Volleyball", "Cross Country", "Girls Tennis", "Girls Golf", "Boys Water Polo", "Girls Water Polo"],
                "winter": ["Boys Basketball", "Girls Basketball", "Boys Soccer", "Girls Soccer", "Wrestling"],
                "spring": ["Baseball", "Softball", "Boys Volleyball", "Boys Tennis", "Track & Field", "Boys Golf", "Swimming", "Boys Volleyball"]
            },
            "has_athletic_forms": True,
            "has_calendar": True,
            "has_schoology_integration": True,
            "upcoming_tryouts": tryouts,
            "raw_content": content[:5000],
        }


async def main():
    """Main entry point for running the scraper."""
    result = await scrape_hamilton_high_athletics()
    print(f"Scraped {result['school_name']}")
    print(f"Mascot: {result['mascot']}")
    print(f"Motto: {result['athletic_motto']}")
    print(f"Athletic Director: {result['athletic_department']['athletic_director']}")
    return result


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
