"""Abraham Lincoln Senior High athletic data scraper.

Generated by discovery agent using Playwright MCP.
School: Abraham Lincoln Senior High School
NCES ID: 062271003139
Website: lincolnhs.org
Athletic URL: https://www.lincolnhs.org/apps/pages/index.jsp?uREC_ID=104855&type=d
Generated: 2026-02-26

Data available:
- Comprehensive sports program (Fall, Winter, Spring)
- Football (Varsity, JV, Flag)
- Volleyball (Girls Varsity/JV, Boys Varsity/JV)
- Basketball (Boys, Girls)
- Soccer (Boys, Girls)
- Baseball/Softball (Varsity, JV)
- Track & Field, Cross Country
- Sports schedules page with links
- MaxPreps integration
- Athletic clearance requirements
"""

from playwright.async_api import async_playwright
import os
from datetime import datetime
import re

# Oxylabs proxy credentials (REQUIRED)
PROXY_SERVER = "ddc.oxylabs.io:8001"
PROXY_USERNAME = os.environ.get("OXYLABS_USERNAME")
PROXY_PASSWORD = os.environ.get("OXYLABS_PASSWORD")


async def scrape_lincoln_high_athletics() -> dict:
    """
    Scrape athletic data from Abraham Lincoln Senior High School website.

    Returns:
        Dict with sports, teams, schedules, and athletic info
    """
    if not PROXY_USERNAME or not PROXY_PASSWORD:
        raise ValueError("Oxylabs credentials not set")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": PROXY_SERVER,
                "username": PROXY_USERNAME,
                "password": PROXY_PASSWORD,
            },
            headless=True,
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )

        page = await context.new_page()

        # Navigate to sports schedules page
        await page.goto("https://www.lincolnhs.org/apps/pages/index.jsp?uREC_ID=104855&type=d&pREC_ID=2393371", wait_until="domcontentloaded")

        content = await page.content()

        # Parse sports by season
        sports_data = {
            "fall": [],
            "winter": [],
            "spring": []
        }

        # Extract sports from the schedule page
        lines = content.split('\n')

        current_season = None
        for line in lines:
            line_upper = line.upper()
            if "FALL SPORTS" in line_upper:
                current_season = "fall"
            elif "WINTER SPORTS" in line_upper:
                current_season = "winter"
            elif "SPRING SPORTS" in line_upper:
                current_season = "spring"
            elif current_season and line.strip():
                # Extract sport names
                sport_match = re.search(r'(Varsity|JV|Girls|Boys)?\s*(Football|Volleyball|Basketball|Soccer|Baseball|Softball|Track|Cross Country|Flag Football)', line, re.IGNORECASE)
                if sport_match:
                    sport = sport_match.group(2)
                    level = sport_match.group(1) or ""
                    if sport and len(sport) > 2:
                        sports_data[current_season].append(f"{level} {sport}".strip())

        # Remove duplicates while preserving order
        for season in sports_data:
            seen = set()
            sports_data[season] = [x for x in sports_data[season] if not (x in seen or seen.add(x))]

        # Extract athletic contact info
        phone_match = re.search(r'Phone:\s*\((\d{3}\)\s*\d{3}-\d{4})', content)
        email_match = re.search(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', content)

        # Look for MaxPreps link
        maxpreps_match = re.search(r'(https://www.maxpreps.com[^\s"]+)', content)

        await browser.close()

        return {
            "nces_id": "062271003139",
            "school_name": "Abraham Lincoln Senior High School",
            "athletic_url": "https://www.lincolnhs.org/apps/pages/index.jsp?uREC_ID=104855&type=d",
            "schedules_url": "https://www.lincolnhs.org/apps/pages/index.jsp?uREC_ID=104855&type=d&pREC_ID=2393371",
            "scraped_at": datetime.now().isoformat(),
            "sports": sports_data,
            "teams": {
                "fall": ["Varsity Football", "JV Football", "Flag Football", "Girls Varsity Volleyball", "Girls JV Volleyball", "Cross Country"],
                "winter": ["Boys Basketball", "Girls Basketball", "Boys Soccer", "Girls Soccer"],
                "spring": ["Varsity Baseball", "JV Baseball", "Varsity Softball", "JV Softball", "Varsity Boys Volleyball", "JV Boys Volleyball", "Track & Field"]
            },
            "athletic_info": {
                "phone": phone_match.group(1) if phone_match else None,
                "has_clearance_process": True,
                "maxpreps_link": maxpreps_match.group(1) if maxpreps_match else None
            },
            "raw_content": content[:5000],
        }


async def main():
    """Main entry point for running the scraper."""
    result = await scrape_lincoln_high_athletics()
    print(f"Scraped {result['school_name']}")
    print(f"Sports: Fall={len(result['sports']['fall'])}, Winter={len(result['sports']['winter'])}, Spring={len(result['sports']['spring'])}")
    print(f"Total teams: {sum(len(v) for v in result['teams'].values())}")
    if result['athletic_info']['maxpreps_link']:
        print(f"MaxPreps: {result['athletic_info']['maxpreps_link']}")
    return result


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
