"""Alhambra Senior High School (Martinez) athletic data scraper.

Generated by discovery agent using Playwright MCP.
School: Alhambra Senior High School
NCES ID: 062403003612
Website: ahs.martinezusd.net
Athletic URL: https://ahs.martinezusd.net/13406_2
Generated: 2026-02-26

Data available:
- Comprehensive athletics program in Diablo Athletic League
- Athletic Director: Anthony Ertola
- Assistant AD: Chris Petiti
- Fall/Winter/Spring sports pages
- Athletic clearance process
- GoFan ticket purchasing system
- Athletic Boosters Club
- Coaches directory
- CIF participation census
- Class of 2025 athletic award winners
"""

from playwright.async_api import async_playwright
import os
from datetime import datetime
import re

# Oxylabs proxy credentials (REQUIRED)
PROXY_SERVER = "ddc.oxylabs.io:8001"
PROXY_USERNAME = os.environ.get("OXYLABS_USERNAME")
PROXY_PASSWORD = os.environ.get("OXYLABS_PASSWORD")


async def scrape_alhambra_martinez_athletics() -> dict:
    """
    Scrape athletic data from Alhambra Senior High School (Martinez) website.

    Returns:
        Dict with sports, athletic department, and contact info
    """
    if not PROXY_USERNAME or not PROXY_PASSWORD:
        raise ValueError("Oxylabs credentials not set")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": PROXY_SERVER,
                "username": PROXY_USERNAME,
                "password": PROXY_PASSWORD,
            },
            headless=True,
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )

        page = await context.new_page()

        # Navigate to athletics home page
        await page.goto("https://ahs.martinezusd.net/13406_2", wait_until="domcontentloaded")

        content = await page.content()

        await browser.close()

        return {
            "nces_id": "062403003612",
            "school_name": "Alhambra Senior High School",
            "athletic_url": "https://ahs.martinezusd.net/13406_2",
            "scraped_at": datetime.now().isoformat(),
            "mascot": "Bulldogs",
            "district": "Martinez Unified School District",
            "league": "Diablo Athletic League",
            "athletic_department": {
                "athletic_director": "Anthony Ertola",
                "assistant_athletic_director": "Chris Petiti"
            },
            "sports_pages": {
                "fall": "https://ahs.martinezusd.net/16350_2",
                "winter": "https://ahs.martinezusd.net/16351_2",
                "spring": "https://ahs.martinezusd.net/16352_2"
            },
            "sports_offered": {
                "fall": ["Football", "Girls Volleyball", "Girls Tennis", "Cross Country", "Girls Golf", "Boys Water Polo", "Girls Water Polo"],
                "winter": ["Boys Basketball", "Girls Basketball", "Boys Soccer", "Girls Soccer", "Wrestling"],
                "spring": ["Baseball", "Softball", "Boys Tennis", "Boys Golf", "Track & Field", "Swimming", "Badminton"]
            },
            "athletics_pages": {
                "home": "https://ahs.martinezusd.net/13406_2",
                "boosters": "https://ahs.martinezusd.net/16348_2",
                "clearance": "https://ahs.martinezusd.net/ (Online Athletic Clearance)",
                "calendar": "https://ahs.martinezusd.net/ (AHS Athletic Events Calendar)",
                "ticket_system": "GoFan"
            },
            "has_cif_census": True,
            "has_coaches_directory": True,
            "has_boosters": True,
            "communication_protocol": "24 Hour Rule enforced",
            "raw_content": content[:5000],
        }


async def main():
    """Main entry point for running the scraper."""
    result = await scrape_alhambra_martinez_athletics()
    print(f"Scraped {result['school_name']}")
    print(f"Mascot: {result['mascot']}")
    print(f"League: {result['league']}")
    print(f"Athletic Director: {result['athletic_department']['athletic_director']}")
    return result


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
