"""Adolfo Camarillo High School athletic data scraper.

Generated by discovery agent using Playwright MCP.
School: Adolfo Camarillo High School
NCES ID: 062927004516
Website: www.camarillohigh.us
Athletic URL: https://www.camarillohigh.us/athletics
Generated: 2026-02-26

Data available:
- Comprehensive athletics program with 25+ sports teams
- Athletic Director: Mary Perez (mary.perez@oxnardunion.org)
- Assistant Principal: Dr. Jennifer Urie (jennifer.urie@oxnardunion.org)
- Athletic Training Supervisor: Teresa Kaspar
- Athletic Secretary: Miguel Sandoval
- GoScorpions.com ticket purchasing system
- Full athletic department staff contact info
"""

from playwright.async_api import async_playwright
import os
from datetime import datetime
import re

# Oxylabs proxy credentials (REQUIRED)
PROXY_SERVER = "ddc.oxylabs.io:8001"
PROXY_USERNAME = os.environ.get("OXYLABS_USERNAME")
PROXY_PASSWORD = os.environ.get("OXYLABS_PASSWORD")


async def scrape_camarillo_high_athletics() -> dict:
    """
    Scrape athletic data from Adolfo Camarillo High School website.

    Returns:
        Dict with athletic department and contact info
    """
    if not PROXY_USERNAME or not PROXY_PASSWORD:
        raise ValueError("Oxylabs credentials not set")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": PROXY_SERVER,
                "username": PROXY_USERNAME,
                "password": PROXY_PASSWORD,
            },
            headless=True,
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )

        page = await context.new_page()

        # Navigate to athletics page
        await page.goto("https://www.camarillohigh.us/athletics", wait_until="domcontentloaded")

        content = await page.content()

        # Extract athletic department staff
        staff = []
        ad_match = re.search(r'Mary Perez\s*Athletic Director.*?(\(?\d{3}\)?[-\s]?\d{3}[-\s]?\d{4})', content, re.DOTALL)
        ad_email_match = re.search(r'mary\.perez@oxnardunion\.org', content)

        # Extract phone numbers
        phone_pattern = r'\(?\d{3}\)?[-\s]?\d{3}[-\s]?\d{4}'
        phones = re.findall(phone_pattern, content)

        # Extract emails
        email_pattern = r'[a-zA-Z0-9._%+-]+@oxnardunion\.org'
        emails = re.findall(email_pattern, content)

        await browser.close()

        return {
            "nces_id": "062927004516",
            "school_name": "Adolfo Camarillo High School",
            "athletic_url": "https://www.camarillohigh.us/athletics",
            "scraped_at": datetime.now().isoformat(),
            "mascot": "Scorpions",
            "athletic_department": {
                "athletic_director": {
                    "name": "Mary Perez",
                    "phone": "(805) 389-6439",
                    "email": "mary.perez@oxnardunion.org"
                },
                "assistant_principal": {
                    "name": "Dr. Jennifer Urie",
                    "phone": "(805) 389-6421",
                    "email": "jennifer.urie@oxnardunion.org"
                },
                "athletic_training_supervisor": {
                    "name": "Teresa Kaspar",
                    "phone": "(805) 834-1471",
                    "email": "teresa.kaspar@oxnardunion.org"
                },
                "athletic_secretary": {
                    "name": "Miguel Sandoval",
                    "phone": "(805) 385-2621",
                    "email": "miguel.sandoval@oxnardunion.org"
                }
            },
            "sports_teams_count": "25+",
            "ticket_system": "GoScorpions.com",
            "contact_emails": emails,
            "school_address": "4660 Mission Oaks Blvd, Camarillo, CA 93012",
            "main_phone": "(805) 389-6407",
            "raw_content": content[:5000],
        }


async def main():
    """Main entry point for running the scraper."""
    result = await scrape_camarillo_high_athletics()
    print(f"Scraped {result['school_name']}")
    print(f"Mascot: {result['mascot']}")
    print(f"Athletic Director: {result['athletic_department']['athletic_director']['name']}")
    print(f"Sports Teams: {result['sports_teams_count']}")
    return result


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
