"""Adrian Wilcox High School athletic data scraper.

Generated by discovery agent using Playwright MCP.
School: Adrian Wilcox High School
NCES ID: 063543006055
Website: wilcox.santaclarausd.org
Athletic URL: https://wilcox.santaclarausd.org/athletics
Generated: 2026-02-26

Data available:
- Comprehensive athletics program with multiple sports
- Athletics calendar
- Athletic participation data
- Coach and Athletic Director contact information
- Sports: Football, Volleyball, Water Polo, Cross Country, Basketball, Soccer, Wrestling, Baseball, Softball, Track, Tennis, Golf, Swimming, Badminton
- Athlete eligibility requirements
"""

from playwright.async_api import async_playwright
import os
from datetime import datetime
import re

# Oxylabs proxy credentials (REQUIRED)
PROXY_SERVER = "ddc.oxylabs.io:8001"
PROXY_USERNAME = os.environ.get("OXYLABS_USERNAME")
PROXY_PASSWORD = os.environ.get("OXYLABS_PASSWORD")


async def scrape_wilcox_high_athletics() -> dict:
    """
    Scrape athletic data from Adrian Wilcox High School website.

    Returns:
        Dict with sports, athletics pages, and contact info
    """
    if not PROXY_USERNAME or not PROXY_PASSWORD:
        raise ValueError("Oxylabs credentials not set")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": PROXY_SERVER,
                "username": PROXY_USERNAME,
                "password": PROXY_PASSWORD,
            },
            headless=True,
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )

        page = await context.new_page()

        # Navigate to athletics page
        await page.goto("https://wilcox.santaclarausd.org/athletics", wait_until="domcontentloaded")

        content = await page.content()

        # Extract athletics subpages
        athletics_pages = [
            "https://wilcox.santaclarausd.org/athletics",
            "https://wilcox.santaclarausd.org/athletics/athletics-calendar",
            "https://wilcox.santaclarausd.org/athletics/athletic-participation-data",
            "https://wilcox.santaclarausd.org/athletics/coach-and-athletic-director-contact"
        ]

        # Check for contact emails
        email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
        emails = re.findall(email_pattern, content)
        school_emails = [e for e in emails if 'santaclarausd' in e.lower()]

        await browser.close()

        return {
            "nces_id": "063543006055",
            "school_name": "Adrian Wilcox High School",
            "athletic_url": "https://wilcox.santaclarausd.org/athletics",
            "scraped_at": datetime.now().isoformat(),
            "mascot": "Chargers",
            "district": "Santa Clara Unified School District",
            "sports_offered": {
                "fall": ["Football", "Girls Volleyball", "Boys Water Polo", "Girls Water Polo", "Cross Country", "Girls Golf", "Girls Tennis"],
                "winter": ["Boys Basketball", "Girls Basketball", "Boys Soccer", "Girls Soccer", "Wrestling"],
                "spring": ["Baseball", "Softball", "Boys Volleyball", "Boys Tennis", "Girls Tennis", "Boys Golf", "Track & Field", "Swimming", "Badminton"]
            },
            "athletics_pages": {
                "homepage": athletics_pages[0],
                "calendar": athletics_pages[1],
                "participation_data": athletics_pages[2],
                "coach_contacts": athletics_pages[3]
            },
            "has_eligibility_requirements": True,
            "has_participation_data": True,
            "contact_emails": school_emails,
            "raw_content": content[:5000],
        }


async def main():
    """Main entry point for running the scraper."""
    result = await scrape_wilcox_high_athletics()
    print(f"Scraped {result['school_name']}")
    print(f"Mascot: {result['mascot']}")
    print(f"District: {result['district']}")
    print(f"Athletics Pages: {len(result['athletics_pages'])}")
    return result


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
