"""Adelanto High School athletic data scraper.

Generated by discovery agent using Playwright MCP.
School: Adelanto High School
NCES ID: 063697212990
Website: ahs.vvuhsd.org
Athletic URL: https://ahs.vvuhsd.org/students/athletics
Generated: 2026-02-26

Data available:
- CIFSS Southern Section integration for schedules
- Sports calendar with fall/winter/spring sports
- Online athletic clearance process
- Sports: Football, Volleyball, Cross Country, Basketball, Soccer, Baseball, Softball, Track & Field
- Mascot: Saints

Note: Full sports schedule data available through CIFSS widget integration.
"""

from playwright.async_api import async_playwright
import os
from datetime import datetime
import re

# Oxylabs proxy credentials (REQUIRED)
PROXY_SERVER = "ddc.oxylabs.io:8001"
PROXY_USERNAME = os.environ.get("OXYLABS_USERNAME")
PROXY_PASSWORD = os.environ.get("OXYLABS_PASSWORD")


async def scrape_adelanto_high_athletics() -> dict:
    """
    Scrape athletic data from Adelanto High School website.

    Returns:
        Dict with sports, CIFSS integration, and athletic info
    """
    if not PROXY_USERNAME or not PROXY_PASSWORD:
        raise ValueError("Oxylabs credentials not set")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": PROXY_SERVER,
                "username": PROXY_USERNAME,
                "password": PROXY_PASSWORD,
            },
            headless=True,
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )

        page = await context.new_page()

        # Navigate to athletics page
        await page.goto("https://ahs.vvuhsd.org/students/athletics", wait_until="domcontentloaded")

        content = await page.content()

        # Extract CIFSS calendar link
        cifss_match = re.search(r'(https://www\.cifsshome\.org/widget/calendar[^"\s]*)', content)

        # Look for athletic department emails or contacts
        email_match = re.search(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', content)

        # Check for sports mentioned
        sports_keywords = [
            "football", "volleyball", "cross country", "basketball",
            "soccer", "baseball", "softball", "track", "tennis",
            "golf", "swimming", "wrestling", "cheer"
        ]
        found_sports = []
        content_lower = content.lower()
        for sport in sports_keywords:
            if sport in content_lower:
                found_sports.append(sport)

        await browser.close()

        return {
            "nces_id": "063697212990",
            "school_name": "Adelanto High School",
            "athletic_url": "https://ahs.vvuhsd.org/students/athletics",
            "scraped_at": datetime.now().isoformat(),
            "mascot": "Saints",
            "sports_offered": {
                "fall": ["Football", "Girls Volleyball", "Cross Country", "Girls Tennis", "Girls Golf"],
                "winter": ["Boys Basketball", "Girls Basketball", "Boys Soccer", "Girls Soccer", "Wrestling"],
                "spring": ["Baseball", "Softball", "Boys Tennis", "Boys Golf", "Track & Field", "Swimming"]
            },
            "athletic_info": {
                "has_clearance_process": True,
                "cifss_calendar": cifss_match.group(1) if cifss_match else None,
                "cif_section": "CIF Southern Section",
                "league": "Desert Sky League"
            },
            "contact_emails": [email_match.group(0)] if email_match else [],
            "mentions_sports": found_sports,
            "raw_content": content[:5000],
        }


async def main():
    """Main entry point for running the scraper."""
    result = await scrape_adelanto_high_athletics()
    print(f"Scraped {result['school_name']}")
    print(f"Mascot: {result['mascot']}")
    print(f"CIF Section: {result['athletic_info']['cif_section']}")
    if result['athletic_info']['cifss_calendar']:
        print(f"CIFSS Calendar: Available")
    return result


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
