"""ATLAS Learning Academy athletic data scraper.

Generated by discovery agent using Playwright MCP.
School: ATLAS Learning Academy
NCES ID: 064214014396
Website: atlas.wpusd.org
Athletic URL: https://atlas.wpusd.org/
Generated: 2026-02-26

Data available:
- Basketball (AAL - Alternative Athletic League)
- Game schedule (vs. Pathways, Confluence, etc.)
- Practice schedule
- Game venue: Hardwood Palace, Rocklin CA

Note: This is an alternative/learning academy that participates in AAL.
"""

from playwright.async_api import async_playwright
import os
from datetime import datetime
import re

# Oxylabs proxy credentials (REQUIRED)
PROXY_SERVER = "ddc.oxylabs.io:8001"
PROXY_USERNAME = os.environ.get("OXYLABS_USERNAME")
PROXY_PASSWORD = os.environ.get("OXYLABS_PASSWORD")


async def scrape_atlas_athletics() -> dict:
    """
    Scrape athletic data from ATLAS Learning Academy website.

    Returns:
        Dict with sports, schedule, and athletic info
    """
    if not PROXY_USERNAME or not PROXY_PASSWORD:
        raise ValueError("Oxylabs credentials not set")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={
                "server": PROXY_SERVER,
                "username": PROXY_USERNAME,
                "password": PROXY_PASSWORD,
            },
            headless=True,
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )

        page = await context.new_page()

        # Navigate to school homepage (athletics info is on homepage calendar)
        await page.goto("https://atlas.wpusd.org/", wait_until="domcontentloaded")

        content = await page.content()

        # Extract basketball games and practices from calendar
        events = []
        event_pattern = r'AAL (Basketball Game|Basketball Practice)([^:]*?:?.*?)(?=AAL|PHS/Atlas|$)'

        # Look for game/practice events with dates and times
        for match in re.finditer(r'AAL (Basketball Game|Basketball Practice)[\s\n]*([^:]*?)[\s\n]*(\d{1,2}:\d{2}\s*(?:AM|PM))[\s\n]*-\s*[\d:]+\s*(?:AM|PM)[\s\n]*,(.*?)?(?=AAL|PHS/Atlas|$)', content, re.DOTALL):
            event_type = match.group(1)
            opponent = match.group(2).strip()
            time = match.group(3)
            location = match.group(4).strip() if match.group(4) else ""

            if "vs." in opponent:
                opponent_clean = re.search(r'vs\.\s*(\w+(?:\s+\w+)?)', opponent)
                if opponent_clean:
                    events.append({
                        "type": event_type,
                        "opponent": opponent_clean.group(1),
                        "time": time,
                        "location": location
                    })
            elif "Practice" in event_type:
                events.append({
                    "type": "Practice",
                    "location": opponent,
                    "time": time
                })

        # Extract venue information
        venue_match = re.search(r'Hardwood Palace[,\s]*(.*?\d{5}.*?)', content)
        venue = venue_match.group(0).strip() if venue_match else "Hardwood Palace, Rocklin, CA"

        await browser.close()

        return {
            "nces_id": "064214014396",
            "school_name": "ATLAS Learning Academy",
            "athletic_url": "https://atlas.wpusd.org/",
            "league": "AAL - Alternative Athletic League",
            "scraped_at": datetime.now().isoformat(),
            "sports": {
                "basketball": {
                    "teams": ["ATLAS Basketball"],
                    "league": "AAL",
                    "events": events[:10]  # Most recent events
                }
            },
            "venues": {
                "primary": venue,
                "notes": "AAL games played at Hardwood Palace, Rocklin CA"
            },
            "raw_content": content[:5000],
        }


async def main():
    """Main entry point for running the scraper."""
    result = await scrape_atlas_athletics()
    print(f"Scraped {result['school_name']}")
    print(f"League: {result['league']}")
    if result['sports']['basketball']['events']:
        print(f"Upcoming events: {len(result['sports']['basketball']['events'])}")
    return result


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
